name: Publish Release
on:
  workflow_dispatch:
  push:
    tags: [ '*' ]
    
permissions:
  contents: write

jobs:
  build:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Get current tag
        run: echo "CURRENT_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Build Windows x86_64
        run: dotnet publish -c Release -r win-x64 --self-contained
      - name: Build Linux x86_64
        run: dotnet publish -c Release -r linux-x64 --self-contained
      - name: Build MacOS x86_64
        run: dotnet publish -c Release -r osx-x64 --self-contained
      - name: Copy Content
        run: |
          cp -r Content bin/Release/net8.0/win-x64/publish
          cp -r Content bin/Release/net8.0/linux-x64/publish
          cp -r Content bin/Release/net8.0/osx-x64/publish
      - name: Create ZIP archives
        run: |
          pushd bin/Release/net8.0/win-x64/publish
          zip -r ../../../../../Celeste64-SpeedrunUtils-${{env.CURRENT_TAG}}-win-x64.zip ./*
          popd
          pushd bin/Release/net8.0/linux-x64/publish
          zip -r ../../../../../Celeste64-SpeedrunUtils-${{env.CURRENT_TAG}}-linux-x64.zip ./*
          popd
          pushd bin/Release/net8.0/osx-x64/publish
          zip -r ../../../../../Celeste64-SpeedrunUtils-${{env.CURRENT_TAG}}-osx-x64.zip ./*
          popd
      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: Celeste 64 SpeedrunUtils v${{env.CURRENT_TAG}}
          body: |
            # Instructions:
            
            - Download and extract the zip file below according to your computer 
            - Run the Celeste64 application from the extracted files
            
            # Requirements:
            
            - **Windows:** 10 or later, x64
            - **Linux:** [Distro support list](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md), x64
            - **Mac:** Monterey or later, x64 Intel-based or Apple Silicon with Rosetta
          files: Celeste64-SpeedrunUtils-*.zip
